ALL_LABELS = sorted([
    'Affiliate License-Licensee',
    'Affiliate License-Licensor',
    'Anti-Assignment',
    'Audit Rights',
    'Cap On Liability',
    'Change Of Control',
    'Competitive Restriction Exception',
    'Covenant Not To Sue',
    'Exclusivity',
    'Expiration Date',
    'Governing Law',
    'Ip Ownership Assignment',
    'Irrevocable Or Perpetual License',
    'Joint Ip Ownership',
    'License Grant',
    'Liquidated Damages',
    'Minimum Commitment',
    'Most Favored Nation',
    'No-Solicit Of Customers',
    'No-Solicit Of Employees',
    'Non-Competition',
    'Non-Disparagement',
    'Non-Transferable License',
    'Post-Termination Services',
    'Price Restrictions',
    'Renewal Term',
    'Revenue/Profit Sharing',
    'Rofr/Rofo/Rofn',
    'Source Code Escrow',
    'Termination For Convenience',
    'Third Party Beneficiary',
    'Uncapped Liability',
    'Unlimited/All-You-Can-Eat-License',
    'Warranty Duration',
    'Work From Home',
])

label2id = {l: i for i, l in enumerate(ALL_LABELS)}
id2label = {i: l for l, i in label2id.items()}
NUM_LABELS = len(ALL_LABELS)